// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Lagomoro_Mission","status":true,"description":"Lagomoro任务系统 V14.0.0 正式版","parameters":{"数据库存储路径":"data/Lagomoro_Mission.xlsx","是否推送任务信息":"true","推送文字设置":"","获得任务时的文字（禁用）":"获得任务：“%1”","完成任务时的文字":"完成任务：“%1”","任务步骤改变时的文字(禁用)":"%1(%2)","获得奖励时的文字":"获得 %1 * %2","金币单位":"金币","经验单位":"经验","困难度文字列表":"[\"简单\",\"一般\",\"中等\",\"困难\",\"超困难！\"]","任务菜单设置":"","上边距":"20","下边距":"20","左边距":"50","右边距":"50","章节列表宽度":"240","菜单显示名称":"任务","地图任务窗口设置":"","左右位置初始状态":"true","上下位置初始状态":"5","窗口宽度":"260","窗口背景颜色":"rgba(0,0,0,0.4)","系统皮肤透明度":"0"}},
{"name":"Lagomoro_Mission_Listener_Pack_01","status":true,"description":"Lagomoro任务系统 监听器包 01","parameters":{"监听获得金钱":"true","监听获得物品":"true","监听获得武器":"true","监听获得防具":"true","监听击杀敌人":"true"}}
];
